name: build

on:
  push:
    paths-ignore:
      - 'docs/**'
    branches:
      - master
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: Setup NodeJS
        uses: actions/setup-node@v7
        with:
          node-version: '24'

      - name: Cache Node.js modules
        uses: actions/cache@v6
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      - run: npm ci --ignore-scripts
      - run: npx prisma generate
      - run: npm run test:cov

      - name: Upload testing reports
        run: |
          bash <(curl -s https://codecov.io/bash)
        env:
          CODECOV_TOKEN: ${{secrets.CODECOV_TOKEN}}
